# Generated by Django 6.0.6 on 2026-06-28 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Music', 'Music'), ('Sports', 'Sports'), ('Cultural', 'Cultural'), ('Workshops', 'Workshops'), ('Business', 'Business'), ('Education', 'Education')], max_length=50)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=300)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
                ('max_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('recently_viewed_by', models.ManyToManyField(blank=True, related_name='recently_viewed_events', to=settings.AUTH_USER_MODEL)),
                ('wishlisted_by', models.ManyToManyField(blank=True, related_name='wishlist_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
