# Generated by Django 6.0.6 on 2026-06-30 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Payment Processing', 'Payment Processing'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Attended', 'Attended'), ('Refunded', 'Refunded')], default='Pending Payment', max_length=30),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='booking_expiry_idx'),
        ),
    ]
